export const RADIAL_MENU_CONSTANTS = {
    ANIMATION_DELAY_STEP: 0.1,
    ANIMATION_DELAY_OFFSET: 0.1,
    CLOSING_ANIMATION_DURATION: 600,
    BUTTON_EDGE_OFFSET: 25,
    BUTTON_CENTER_OFFSET: 20,
    START_ANGLE_OFFSET: Math.PI / 2,
} as const
